# Generated by Django 6.0.7 on 2026-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
