# Generated by Django 6.0.7 on 2026-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='name',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='ticket_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(fields=('event', 'ticket_type'), name='event_ticket_type_unique'),
        ),
    ]
