# Generated by Django 6.0.7 on 2026-08-23 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.PositiveIntegerField()),
                ('platform_fee', models.PositiveIntegerField()),
                ('payment_fee', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='orders.order')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
