# Generated by Django 6.0.7 on 2026-08-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('EVENT_CREATED', 'Event Created'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('ORDER_PAID', 'Order Paid'), ('REFUND_CREATED', 'Refund Created'), ('INVENTORY_UPDATED', 'Inventory Updated')], max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
