# Generated by Django 6.0.7 on 2026-08-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_CREATED', 'Event Created'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('ORDER_PAID', 'Order Paid'), ('REFUND_CREATED', 'Refund Created'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('USER_REGISTERED', 'User Registered')], max_length=255),
        ),
    ]
