# Generated by Django 6.0.7 on 2026-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_CREATED', 'Event Created'), ('EVENT_PUBLISHED', 'Event Published'), ('TICKET_TYPE_CREATED', 'Ticket Type Created'), ('INVENTORY_UPDATED', 'Inventory Updated'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('RESERVATION_CANCELLED', 'Reservation Cancelled'), ('ORDER_PAID', 'Order Paid'), ('REFUND_CREATED', 'Refund Created'), ('USER_REGISTERED', 'User Registered'), ('PAYMENT_SUCCESS', 'Payment Success'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated')], max_length=255),
        ),
    ]
