# Generated by Django 6.0.7 on 2026-08-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.PositiveIntegerField()),
                ('platform_fee', models.PositiveIntegerField()),
                ('payment_fee', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
